FROM nvidia/cuda:10.1-devel as buildenv

RUN apt-get update
RUN apt-get install -y \
    git \
    python \
    python-pip \
    libpython-dev

RUN pip install virtualenv
RUN virtualenv /usr/local
RUN rm -rf /usr/local/local

##############################################################
# Create a new image based on only the executable parts of the old image
FROM nvidia/cuda:10.1-runtime

RUN apt-get update && \
    apt-get install -y \
    python

#############################################################
## This looks odd, but as the CUDA is in /usr/local I don't want to
## copy the big heavy devel CUDA into the runtime
WORKDIR /usr/local/bin
COPY --from=buildenv /usr/local/bin .
WORKDIR /usr/local/include
COPY --from=buildenv /usr/local/include .
WORKDIR /usr/local/lib
COPY --from=buildenv /usr/local/lib .

RUN ldconfig
